#!/bin/sh
# Name : Batch 24 CMR

HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4
BACKTITLE="SCANMASTER"
TITLE="Scanmaster Menu"
MENU="Choose one of the following options:"

OPTIONS=(
1 "Target Selection"
2 "Port Selection"
3 "Scan Types"
4 "Service and Operating System Detection"
5 "Output formats"
6 "NSE Scripting"
7 "HTTP info gathering"
8 "Timing and Performance"
9 "SLL Labs Testing"
)

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
        read -p "    └──╼ Enter selection [0-9] > "
            echo "You chose Option 1"
            ;;
        2)
            echo "You chose Option 2"
            ;;
        3)
            echo "You chose Option 3"
            ;;
esac
